[connection-bond0-mtu]
match-device=interface-name:bond0
ethernet.mtu=9000

[connection-eno1-mtu]
match-device=interface-name:eno1
ethernet.mtu=9000

[connection-eno2-mtu]
match-device=interface-name:eno2
ethernet.mtu=9000
